services:
  
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: amarillo_database
    env_file: ".env"
    networks:
      - amarillo-network
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  amarillo-network:
    driver: bridge